### ISSUE TITLE
CustomHotbar module prevents the renderHotbar hook from firing in Firefox

### ISSUE THREAD

**Issue by illandril** [Norc/foundry-custom-hotbar#74]
This...
```
Hooks.on("init", async () => {
  CONFIG.ui.hotbar = class extends Hotbar {
    _onDragStart(...arg) {
      document.getElementsByClassName("tooltip")[0].style.display = "none";
      super._onDragStart(...arg);
    }
  };
});
```
... seems to cause Firefox to think the Hotbar's constructor's name is the empty string, while Chrome still thinks it is named Hotbar. This causes the `renderHotbar` hook to fire as simply `render` for Firefox, breaking every other module that depends on the `renderHotbar` hook.

Example issue: https://github.com/illandril/FoundryVTT-hotbar-uses/issues/12

Changing the class line to this seems to correct the issue (I only very, very quickly tested this, so this may cause other issues)... 
```
  CONFIG.ui.hotbar = class Hotbar extends Hotbar {
```

This can be worked around by listening to the `render` hook and checking to see if the first argument is the hotbar, in addition to listening to the `renderHotbar` hook (which I plan on implementing for my module even if you do fix this, as a safeguard against other hotbar modules causing the same issue).

**Comment by Norc** [comment]
Nice, thanks so much for the detailed feedback. I'll take a stab at incorporating this tonight.

**Comment by Norc** [comment]
I've implemented this fix for the next version, closing but will reopen/revisit if needed.

**Comment by Norc** [comment]
@illandril , I had to revert this fix for now because it was causing additional issues. Can you confirm you're still seeing this in the latest Firefox before I dig into it more (later, sadly?)

**Comment by illandril** [comment]
I am still seeing this in the latest Firefox (82.0).

With this...
```
  ['render', 'renderHotbar', 'renderCustomHotbar'].forEach(hookName => {
    Hooks.on(hookName, (hotbar) => {
      const isStandardHotbar = hotbar === ui.hotbar;
      const isCustomHotbar = hotbar === ui.customHotbar;
      console.log(`${hookName}: isStandardHotbar=${isStandardHotbar}, isCustomHotbar=${isCustomHotbar}`)
    });
  });
```
... I'd expect to see `render` never called, `renderHotbar` called for both the custom and standard hotbar (in 0.7.5 only... in 0.6.x it wouldn't be expected for the custom hotbar), and `renderCustomHotbar` called for only the custom hotbar.

I correctly see both the `renderHotbar` and `renderCustomHotbar` hooks called for the custom hotbar, but see the `render` hook for the standard hotbar.


This is the workaround I've been using in my module (which still works "good enough" for me, so definitely no rush on having this fixed as far as I'm concerned): https://github.com/illandril/FoundryVTT-hotbar-uses/blob/f08aba7a364502106665a9b32dd926be4a7130f1/init.js#L46

**Comment by Norc** [comment]
Awesome, thanks so much for the extra info and checks!! I"ll look into this once the dust settles a bit from the 0.7.5 release.

**Comment by Norc** [comment]
Can anyone confirm this is still an issue in Firefox?

**Comment by illandril** [comment]
I just checked Firefox 87, it still happens.

**Comment by Norc** [comment]
Thanks for that. I think I have a solution that should bypass this issue completely and will work to have it out within the next week finally.

**Comment by Norc** [comment]
I was able to avoid overriding the Hotbar class at all by adding a single event listener. In addition to solving this issue, it's just a much better solution in general.

I was able to reproduce this issue in FireFox before my fix, and was unable to reproduce it after. Closing this one, I think the new version will finally zonk it.
